name: jjpricejj
favicon: null
layout_spectrum: 0.32470185216516256
typography_spectrum: 0.2842438977677375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9495549616403878
  lightness: 0.5448121463414282
  saturation: 0.0017148288898169994
  rhythmicContrast: 0.9628837432246655
purpose: []
